name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
#cambios 
      - name: Build Frontend
        run: |
          docker build -t tienda-frontend ./frontend
          docker tag tienda-frontend:latest 487818027813.dkr.ecr.us-east-1.amazonaws.com/tienda-frontend:eks-v2  
          


      - name: Push Frontend
        run: |
          docker push 487818027813.dkr.ecr.us-east-1.amazonaws.com/tienda-frontend:eks-v2

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --region us-east-1 --name devopseks

      - name: Restart Frontend Deployment
        run: |
          kubectl rollout restart deployment tienda-frontend -n tienda
          kubectl rollout status deployment tienda-frontend -n tienda

